const sweetAlertDefaultParams = {
  customClass: {
    // container: '...',
    // popup: '...',
    // header: '...',
    // title: '...',
    // closeButton: '...',
    // icon: '...',
    // image: '...',
    // htmlContainer: '...',
    // input: '...',
    // inputLabel: '...',
    // validationMessage: '...',
    // actions: '...',
    confirmButton: 'btn btn-primary btn-lg',
    // denyButton: '...',
    // cancelButton: '...',
    // loader: '...',
    // footer: '....',
    // timerProgressBar: '....',
  },
  buttonsStyling: false,
  // title: '',
  // text: '',
  // type: null,
  // allowOutsideClick: false,
  // showConfirmButton: true,
  // showCancelButton: false,
  // closeOnConfirm: true,
  // closeOnCancel: true,
  // confirmButtonText: 'OK',
  // confirmButtonColor: '#8CD4F5',
  // cancelButtonText: 'Cancel',
  // imageUrl: null,
  // imageSize: null,
  // timer: null,
  // html: false,
  // animation: true,
  // allowEscapeKey: true,
  // inputType: 'text',
  // inputPlaceholder: '',
  // inputValue: '',
  // showLoaderOnConfirm: false
}

export { sweetAlertDefaultParams }
